[general]

live_config_reload = true

##### Theming (Third-party)
## From: https://github.com/alacritty/alacritty-theme

# light theme - switch to this when working outdoors/in a bright area
# "~/.config/alacritty/themes/themes/ashes_light.toml"
# default dark theme
# "~/.config/alacritty/themes/themes/tomorrow_night.toml",
import = [
  "~/.config/alacritty/themes/themes/tomorrow_night.toml",
]

##### End Theming

[window]

opacity = 1.0
padding.x = 5
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

dynamic_title = false

### End Main config

### Basic customizations

[font]

normal.family = "Iosevka Nerd Font"
bold.family = "Iosevka Nerd Font"
italic.family = "Iosevka Nerd Font"
bold_italic.family = "Iosevka Nerd Font"

size = 14.0

### End Basic customizations

##### Issues / Notes
### Alacritty known issues
# 1. Doesn't update existing instances when gnome text-scaling-factor is changed <https://github.com/alacritty/alacritty/issues/5303>
#####


