#!/bin/bash
# (c) Anon Ray <rayanon@riseup.net>
# BSD Licensed. See LICENSE file for more details.

# Script to bootstrap my environment.
# This installs required tools and sets up various dotfiles. This also assumes
# it is a barebones Linux machine with bash available.

# Check if zsh, tmux, vim, git are installed. If not install them.
# Create symlinks from files inside this repo to config file in user's home
# directory

set -e

# These are the requirements for my environ
CORE_REQUIREMENTS=(zsh tmux vim git emacs ssh htop tree neovim)

is_installed() {
  req=$1
  # To find out a program is installed from shell script might not be
  # straightforward and consistent. See this answer for more details:
  # http://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script#677212
  if $(command -v "$req" > /dev/null); then # if found
    return 0
  else
    return 1
  fi
}

find_linux_distro() {
  distrib_id=$(cat /etc/*-release | uniq -u | grep -Po 'DISTRIB_ID=\K.*')
}

check_core_requirements() {
  for req in "${CORE_REQUIREMENTS[@]}"
  do
    if ! $(is_installed $req); then
      to_install=( "${to_install[@]}" $req )
    fi
  done
  if [ -z "${to_install[0]}" ]; then
    echo "All requirements satisfy.."
    return 0
  else
    return 1
  fi
}

install_core_requirements() {
  packages=(${to_install[@]})

  # Check the system - and decide the package manager
  # TODO: add arch
  if $(is_installed apt-get); then # apt based distro
    package_manager="apt-get"
  elif $(is_installed yum); then # yum based distro
      package_manager="yum"
  elif $(is_installed pacman); then # arch linux
      package_manager="pacman"
  fi
  if [ -z "$package_manager" ]; then
    echo "Oops! Could not find any known package manager!"
    echo "Maybe you can modify the script to add your package manager.."
    exit 1
  fi

  echo "Found package manager: $package_manager"
  echo "Packages to be insalled: ${packages[@]}"
  read -p "Continue? [y/N]: "

  if [ $REPLY != "y" ]; then
    echo "Installation aborted."
    exit 0
  fi

  if [ $package_manager == "pacman" ]; then
    echo "sudo pacman -S ${packages[@]}"
    sudo pacman -S --noconfirm ${packages[@]}
  else
    echo "sudo $package_manager install -y ${packages[@]}"
    # System-wide installation; use sudo
    sudo $package_manager install -y ${packages[@]}
  fi
}

create_symlinks() {
  echo "Creating symlinks for necessary files.."
  ln -sf ~/dotfiles/vim ~/.vim
  ln -sf ~/dotfiles/vim/vimrc ~/.vimrc
  ln -sf ~/dotfiles/zshrc ~/.zshrc
  ln -sf ~/dotfiles/zshenv ~/.zshenv
  ln -sf ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
  ln -sf ~/dotfiles/tmux/init.sh ~/.tmux-session-init.sh
  ln -sf ~/dotfiles/tmux/tmuxline.conf ~/.tmuxline.conf
  ln -sf ~/dotfiles/gitconfig ~/.gitconfig
  ln -sf ~/dotfiles/aliases ~/.aliases
  ln -sf ~/dotfiles/doom.d ~/.doom.d
}


# install extras
oh_my_zsh_dir="$HOME/.oh-my-zsh"
zsh_pure_dir="$HOME/.zsh/pure"

install_zsh_extras() {
  repo_url="https://github.com/ohmyzsh/ohmyzsh.git"
  echo "Cloning oh-my-zsh.."
  git clone $repo_url $oh_my_zsh_dir

  pure_repo_url="https://github.com/sindresorhus/pure.git"
  echo "Cloning zsh-pure theme.."
  git clone $pure_repo_url $zsh_pure_dir

  source ~/.zshrc
}

install_doom_emacs() {
  doom_repo_url="https://github.com/doomemacs/doomemacs"
  echo "Cloning doom emacs..."
  git clone --depth 1 "$doom_repo_url" "~/.emacs.d"
  echo "Setting up doom emacs..."
  ~/.emacs.d/bin/doom sync
}

set_zsh_default() {
  echo "Setting zsh to be default shell.."
  chsh -s $(which zsh)
}

# main install function
install() {
  if check_core_requirements; then
    if [ ! -d $oh_my_zsh_dir ]; then
      set_zsh_default && install_zsh_extras
    fi
    create_symlinks && set_zsh_default
    exit 0 # all requirements satisfy
  else
    install_core_requirements \
      && create_symlinks \
      && install_doom_emacs \
      && set_zsh_default \
      && install_zsh_extras

    echo "Done"
    exit 0
  fi
}

install
