#!/bin/bash

# Script to bootstrap my dev environment.  This installs required tools and sets
# up various dotfiles. This also assumes it is a barebones Linux machine with
# bash available.

# It does the following -
# - Install required software packages for development (e.g. zsh, tmux, vim, git
# etc.)
# - Create symlinks. The standard config files/dotfiles in $HOME are symlinked
# to files in this # repo.

set -euox pipefail

# First we install

# These are the requirements for my environ
CORE_REQUIREMENTS=(zsh tmux tmuxp vim git emacs ssh htop tree neovim alacritty ripgrep fd fzf ttf-iosevka-nerd)

is_installed() {
  req=$1
  # To find out a program is installed from shell script might not be
  # straightforward and consistent. See this answer for more details:
  # http://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script#677212
  if $(command -v "$req" > /dev/null); then # if found
    return 0
  else
    return 1
  fi
}

check_core_requirements() {
  for req in "${CORE_REQUIREMENTS[@]}"
  do
    if ! $(is_installed "$req"); then
      to_install=( "${to_install[@]}" $req )
    fi
  done
  if [ -z "${to_install[@]}" ]; then
    echo "All requirements satisfy.."
    return 0
  else
    return 1
  fi
}

check_package_manager() {
  # Check if current system is Arch-based; if not, abort
  if $(is_installed pacman); then # arch-based distro
    return 0;
  else
    echo "Oops, not an Arch-based system! Currently on Arch-based distros are supported."
    echo "Feel free to submit a PR, if you want to add new support."
    exit 1
  fi
}

install_core_requirements() {
  check_package_manager
  packages=(${to_install[@]})
  echo "Packages to be insalled: ${packages[@]}"
  read -p "Continue? [y/N]: "

  if [ "$REPLY" != "y" ]; then
    echo "Installation aborted."
    exit 0
  fi

  echo "sudo pacman -S ${packages[@]}"
  sudo pacman -S --noconfirm ${packages[@]}
}

create_symlinks() {
  echo "Creating symlinks for necessary files.."
  ln -sf ~/dotfiles/alacritty/alacritty.toml ~/.config/alacritty.toml
  ln -sf ~/dotfiles/vim ~/.vim
  ln -sf ~/dotfiles/vim/vimrc ~/.vimrc
  ln -sf ~/dotfiles/zsh/zshrc ~/.zshrc
  ln -sf ~/dotfiles/zsh/zshenv ~/.zshenv
  ln -sf ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
  ln -sf ~/dotfiles/tmux/tmuxline.conf ~/.tmuxline.conf
  ln -sf ~/dotfiles/tmux/tmuxp ~/.tmuxp
  ln -sf ~/dotfiles/git/gitconfig ~/.gitconfig
  ln -sf ~/dotfiles/shell/aliases ~/.aliases
  mkdir -p ~/.stack/templates
  ln -sf ~/dotfiles/stack/config.yaml ~/.stack/config.yaml
  ln -sf ~/dotfiles/stack/anonray.hsfiles ~/.stack/templates/anonray.hsfiles
}

# install extra tools that are not in the package manager; git clone and install step..
install_from_git_repo() {
  name="$1"
  repo_url="$2"
  clone_dir="$3"
  if [[ -z "$name" || -z "$repo_url" || -z "$clone_dir" ]]; then
    echo "WARN: Not all required arguments are passed to $0"
    echo "WARN: Skipping git clone..."
    return;
  fi
  echo "Cloning $name.."
  git clone --depth 1 "$repo_url" "$clone_dir"
}

install_doom_emacs() {
  echo "Installing doom emacs..."
  install_from_git_repo "doom emacs" "https://github.com/doomemacs/doomemacs" "$HOME/.emacs.d"
  echo "Setting up doom emacs..."
  ln -sf ~/dotfiles/doom.d ~/.doom.d
  "$HOME/.emacs.d/bin/doom install"
  "$HOME/.emacs.d/bin/doom sync"
}

install_alacritty_themes() {
  echo "Installing alacritty themes..."
  install_from_git_repo "alacritty themes" "https://github.com/alacritty/alacritty-theme" "$HOME/.config/alacritty/themes"
}

install_extra_requirements() {
  install_alacritty_themes \
    && install_doom_emacs
}

set_zsh_default() {
  echo "Setting zsh to be default shell.."
  sudo chsh -s "$(which zsh)" "$(whoami)"
}

# main install function
install() {
  if check_core_requirements; then
    set_zsh_default \
      && install_extra_requirements \
      && create_symlinks
    exit 0 # all requirements satisfy
  else
    install_core_requirements \
      && install_extra_requirements \
      && create_symlinks
    echo "Done"
    exit 0
  fi
}

install
