" This is a collection over time, from dotfiles from various sources
" - Anon Ray (ecthiender) <rayanon004@gmail.com>


" core vim settings and config

set nocompatible " be - IMproved!

set encoding=utf8 " because the whole world isn't english


" init the runtime/package manager neobundle
source ~/.vim/plug-init.vim

filetype plugin indent on " Enable filetype detection

" turn syntax highlighting on
syntax on

set wildmenu "Turn on Wild menu

set wildignore+=*/tmp/*,*.so,*.swp,*.pyc

set autoread "Set to auto read when a file is changed from the outside

set hlsearch "highlight pattern when searching
set incsearch "incremental search
set ruler "Always show current position

" Tab settings to insert spaces instead of tabs
" and each tab is 2 spaces
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
%retab

"set smarttab
"set autoindent
"set smartindent

" text should break to new line after 79 char
set textwidth=79
set formatoptions+=t

"set foldmethod=indent

set magic "Set magic on for regex
set ignorecase "ignore case when searching
set smartcase "see :help smartcase

set laststatus=2  " Always show status line

" Omnicompletion
set omnifunc=syntaxcomplete#Complete

" use 256 terminal colors
set t_Co=256

" background theme and colorscheme
set background=dark
colorscheme jellybeans
"colorscheme swamplight
"set background=dark
"colorscheme solarized

set cmdheight=1 "The commandbar height

" No backups, swap files etc!
set noswapfile
set nobackup

if exists("&undodir")
  set undodir=~/.vim/undo
endif

" Optimize for fast terminal connections
set ttyfast

" Show the filename in the window titlebar
set title

" turn off all error bells and visual bells
set noerrorbells
set visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" use the mouse
set mouse=a

"Save when losing focus
set autowriteall " Auto-save files when switching buffers or leaving vim.
au FocusLost * silent! :wa
au TabLeave * silent! :wa

" Resize splits when the window is resized
au VimResized * exe "normal! \<c-w>="

set hidden " Allow un-saved buffers in background
set showmatch " set show matching parenthesis
set noshowmatch "stop it from matching the previous bracket by going back to it

"highlight current line
set cursorline

" Highlight VCS conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'

"disable Esc
"inoremap <esc> <nop>

"Better Exit from insert mode
"inoremap jk <Esc>
"inoremap kj <Esc>

"Fix those pesky situations where you edit & need sudo to save
cmap w!! w !sudo tee % >/dev/null

" set leader
let mapleader = ","
let g:mapleader = ","


" load plugin configs
source ~/.vim/plugins-config.vim

" load custom mappings
source ~/.vim/custom-mappings.vim
