" This is a collection over time, from dotfiles from various sources


" core vim settings and config

set nocompatible " be - IMproved!

set encoding=utf8 " because the whole world isn't english


" init the runtime/package manager neobundle
source ~/.vim/neobundle-init.vim


filetype plugin indent on " Enable filetype detection

syntax on

set wildmenu "Turn on Wild menu

set autoread "Set to auto read when a file is changed from the outside

set hlsearch "highlight pattern when searching
set incsearch "incremental search
set ruler "Always show current position

" Tab settings to insert spaces instead of tabs
" and each tab is 2 spaces
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
%retab
"set smarttab
"set autoindent
"set smartindent
set textwidth=79
set formatoptions+=t
"set foldmethod=indent

set magic "Set magic on for regex
set ignorecase "ignore case when searching
set smartcase "see :help smartcase

set laststatus=2  " Always show status line

" Omnicompletion
set omnifunc=syntaxcomplete#Complete

set t_Co=256

set background=dark
colorscheme jellybeans

set cmdheight=2 "The commandbar height

" Centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
  set undodir=~/.vim/undo
endif

" Optimize for fast terminal connections
set ttyfast

" Show the filename in the window titlebar
set title

" turn off all error bells and visual bells
set noerrorbells
set visualbell t_vb=

autocmd GUIEnter * set visualbell t_vb=

" use the mouse
set mouse=a

" set leader
let mapleader = ","
let g:mapleader = ","


" load plugin configs
source ~/.vim/plugins-config.vim

" load custom mappings
source ~/.vim/custom-mappings.vim
